# Generated by Django 3.0.8 on 2021-06-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210625_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telephone',
            new_name='tel',
        ),
    ]
