# Generated by Django 3.0.8 on 2021-06-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210625_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False, verbose_name='Admin?'),
        ),
    ]
