# Generated by Django 3.0.8 on 2021-06-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210624_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sortno',
            new_name='buying_price',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Non classifié', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
