# Generated by Django 3.0.8 on 2021-06-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210626_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
